- ping:
    _name: ping1
    _kwargs:
      destination: 10.10.12.2
    success:
      packet_loss: 0
    _mode: strict

    _name: ping2
    _kwargs:
      destination: 10.10.13.3
    success:
      packet_loss: 0
    _mode: strict
