---
- get_bgp_neighbors:
    global:
      peers:
        10.10.12.2:
          is_enabled: true
          is_up: true
          remote_as: 65512
        10.10.13.3:
          is_enabled: true
          is_up: true
          remote_as: 65513
